In [1]:
%load_ext snowframe

SnowFrame magic loaded. Use %%snowframe or %%sf in any cell.

In [2]:
import pandas as pd
from snowframe import SnowFrame, set_active_session

sales = pd.DataFrame({
    "customer_id": [1, 1, 2, 3, 3],
    "amount": [100, 2500, 700, 1800, 300],
})

customers = pd.DataFrame({
    "customer_id": [1, 2, 3],
    "name": ["Amit", "Riya", "Kabir"],
})

In [3]:
sales

   customer_id  amount
0            1     100
1            1    2500
2            2     700
3            3    1800
4            3     300

In [4]:
customers

   customer_id   name
0            1   Amit
1            2   Riya
2            3  Kabir

In [5]:
sf = SnowFrame()
sf.auto()
set_active_session(sf)

sf.tables()

  table_name
0  customers
1      sales

In [8]:
%%sf

select * from customers;

   customer_id   name
0            1   Amit
1            2   Riya
2            3  Kabir

In [10]:
%%sf
select * from sales;

   customer_id  amount
0            1     100
1            1    2500
2            2     700
3            3    1800
4            3     300

In [22]:
%%sf
create or replace table final_merged as 
select a.*,b.name from (select * from sales) a
left join (select * from customers) b
on a.customer_id=b.customer_id;

Done.  Tables: ['customers', 'final_merged', 'sales']

In [23]:
%%sf

SELECT *
FROM final_merged;

   customer_id  amount   name
0            1     100   Amit
1            1    2500   Amit
2            2     700   Riya
3            3    1800  Kabir
4            3     300  Kabir

In [24]:
final_merged

NameError: name 'final_merged' is not defined

In [25]:
final_merged_df = sf.to_df("final_merged")
final_merged_df

   customer_id  amount   name
0            1     100   Amit
1            1    2500   Amit
2            2     700   Riya
3            3    1800  Kabir
4            3     300  Kabir

In [26]:
final_merged_df

   customer_id  amount   name
0            1     100   Amit
1            1    2500   Amit
2            2     700   Riya
3            3    1800  Kabir
4            3     300  Kabir

In [27]:
type(final_merged_df)

pandas.DataFrame